name: gitleaks
on:
  pull_request:
    branches:
        - 'main'
        - 'develop'
  push:
    branches:
        - 'main'
        - 'develop'
  workflow_dispatch:

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
